2017-06-02 13:05:54  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 146, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

